### ISSUE TITLE
Remove dependency on GPL SharpZipLib

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/metadata-extractor-dotnet#48]
(Migrated from drewnoakes/metadata-extractor#170)

@yschkatula pointed out that SharpZipLib is GPL, while this project is Apache.

The project should be updated to not have such a restrictive dependency.

**Comment by drewnoakes** [comment]
By the way SharpZipLib is only used for deflate, and only in PCL builds.

Feel free to change this.

**Comment by yschkatula** [comment]
Besides, this may be a way to go: https://blogs.msdn.microsoft.com/dotnet/2013/06/06/portable-compression-and-httpclient-working-together

**Comment by kwhopper** [comment]
Microsoft.Bcl.Compression might work, but it doesn't support Silverlight 5 as a target and it is selected in the portable project. However, if that target is removed IConvertible is no longer compatible and must be removed as well. @drewnoakes will have to evaluate whether that's desirable.

**Comment by petersondrew** [comment]
I have not tested it for stability, but someone has ported the Zlib implementation from DotNetZip to a PCL https://github.com/advancedrei/Zlib.Portable .

If removing support for Silverlight 5 as a target is acceptable, I would be more than happy to jump on that and submit a PR as we want to ship a product using metadata extractor.

**Comment by drewnoakes** [comment]
That would be great. Go for it.

**Comment by petersondrew** [comment]
So after sniffing around, it looks like the only place SharpZipLib is referenced is `PngMetadataReader`. Does that sound about right?

**Comment by petersondrew** [comment]
I've pushed a commit to fix this, but it doesn't have any test coverage as the tests for PngMetadataReader do not test for an `iCCP` directory and whether it can read it. I have to admit my lack of expertise on metadata formats/directories here and ask guidance on how to properly test this change.

**Comment by drewnoakes** [comment]
Looks good. I'm also confused why Zlib.Portable wasn't used directly. Can't think of a reason.

When testing I run the lib against the sample image library:

https://github.com/drewnoakes/metadata-extractor-images

There's a utility in the project that overwrites the `metadata/*.txt` files, and you can run a diff to see if any regressions have popped in.

Caveat is that the images repo is used by both the Java and C# versions, and there are a few differences (though fewer over time). You should review to make sure there are no differences in PNG images related to ICC/TXT tags. Alternatively (probably better) you could run before/after your changes and diff those.

**Comment by drewnoakes** [comment]
Picking this up again after a busy spell. Apologies for the delay.

The most thorough way of testing changes is described here:

https://github.com/drewnoakes/metadata-extractor/wiki/Working-with-test-images

**Comment by drewnoakes** [comment]
Just tried out your change and it looks good so far. Will try to get it into the 1.5 release today.

**Comment by drewnoakes** [comment]
This change does actually fail a regression test, though I'm not sure it's critical.

The file `/png/metadata/invalid-iccp-missing-adler32-checksum.png` has, as the name suggests, a missing checksum. Before this change, the ICC data was decoded correctly, despite an error message about the checksum. After this change, there's still an error message but the ICC data is not decoded.

```diff
diff --git a/png/metadata/invalid-iccp-missing-adler32-checksum.png.txt b/png/metadata/invalid-iccp-missing-adler32-checksum.png.txt
index 2351d77..295742b 100644
--- a/png/metadata/invalid-iccp-missing-adler32-checksum.png.txt
+++ b/png/metadata/invalid-iccp-missing-adler32-checksum.png.txt
@@ -1,6 +1,6 @@
 FILE: invalid-iCCP-missing-adler32-checksum.png
 
-[ERROR: ICC Profile] Exception reading ICC profile: Unexpected EOF
+[ERROR: ICC Profile] Exception reading ICC profile: Block length does not match with its complement.
 
 [PNG-IHDR - 0x0001] Image Width = 460
 [PNG-IHDR - 0x0002] Image Height = 60
@@ -10,34 +10,6 @@ FILE: invalid-iCCP-missing-adler32-checksum.png
 [PNG-IHDR - 0x0006] Filter Method = Adaptive
 [PNG-IHDR - 0x0007] Interlace Method = No Interlace
 
-[ICC Profile - 0x0000] Profile Size = 3144
-[ICC Profile - 0x0004] CMM Type = Lino
-[ICC Profile - 0x0008] Version = 2.1.0
-[ICC Profile - 0x000c] Class = Display Device
-[ICC Profile - 0x0010] Color space = RGB 
-[ICC Profile - 0x0014] Profile Connection Space = XYZ 
-[ICC Profile - 0x0018] Profile Date/Time = 1998:02:09 06:49:00
-[ICC Profile - 0x0024] Signature = acsp
-[ICC Profile - 0x0028] Primary Platform = Microsoft Corporation
-[ICC Profile - 0x0030] Device manufacturer = IEC 
-[ICC Profile - 0x0034] Device model = sRGB
-[ICC Profile - 0x0044] XYZ values = 0.964 1 0.825
-[ICC Profile - 0x0080] Tag Count = 17
-[ICC Profile - 0x63707274] Copyright = Copyright (c) 1998 Hewlett-Packard Company
-[ICC Profile - 0x64657363] Profile Description = sRGB IEC61966-2.1
-[ICC Profile - 0x77747074] Media White Point = (0.9505, 1, 1.0891)
-[ICC Profile - 0x626b7074] Media Black Point = (0, 0, 0)
-[ICC Profile - 0x7258595a] Red Colorant = (0.4361, 0.2225, 0.0139)
-[ICC Profile - 0x6758595a] Green Colorant = (0.3851, 0.7169, 0.0971)
-[ICC Profile - 0x6258595a] Blue Colorant = (0.1431, 0.0606, 0.7141)
-[ICC Profile - 0x646d6e64] Device Mfg Description = IEC http://www.iec.ch
-[ICC Profile - 0x646d6464] Device Model Description = IEC 61966-2.1 Default RGB colour space - sRGB
-[ICC Profile - 0x76756564] Viewing Conditions Description = Reference Viewing Condition in IEC61966-2.1
-[ICC Profile - 0x76696577] Viewing Conditions = view (0x76696577): 36 bytes
-[ICC Profile - 0x6c756d69] Luminance = (76.0365, 80, 87.1246)
-[ICC Profile - 0x6d656173] Measurement = 1931 2° Observer, Backing (0, 0, 0), Geometry Unknown, Flare 1%, Illuminant D65
-[ICC Profile - 0x74656368] Technology = CRT 
-
 [PNG-iCCP - 0x000c] ICC Profile Name = Photoshop ICC profile
 
 [PNG-gAMA - 0x000b] Image Gamma = 0.455

warning: LF will be replaced by CRLF in png/metadata/invalid-iccp-missing-adler32-checksum.png.txt.
The file will have its original line endings in your working directory.
```

**Comment by drewnoakes** [comment]
ZLib, GZip and deflate are different beasts. Some discussion here: http://stackoverflow.com/a/21544269/24874

This will take more time than I have before 1.5, so I'll skip it for now. I've pulled your branch, rebased it and updated the nuspec file.

https://github.com/drewnoakes/metadata-extractor-dotnet/tree/replace-sharpziplib

**Comment by drewnoakes** [comment]
In moving to netstandard (currently available on NuGet as `2.0.0-rc1`) I've removed the dependency altogether. 

Actually in the end the licensing concern is moot, as they're moving to MIT. However they don't have a `netstandard`-ready build available on NuGet yet, and there's no timeline for doing so, so I removed the lib and accept that the one case of ICC data embedded in a PNG file that is missing the Adler checksum (and so I believe is invalid anyway) doesn't parse any more. In future, this might be addressed.

I'd appreciate feedback/testing of the RC build.
